insert into age_rating_organizations
(name, id)
values ('ESRB', 1),
       ('PEGI', 2),
       ('CERO', 3),
       ('USK', 4),
       ('GRAC', 5),
       ('CLASS_IND', 6),
       ('ACB', 7);

insert into age_ratings
    (name, id)
values ('Three', 1),
       ('Seven', 2),
       ('Twelve', 3),
       ('Sixteen', 4),
       ('Eighteen', 5),
       ('RP', 6),
       ('EC', 7),
       ('E', 8),
       ('E10', 9),
       ('T', 10),
       ('M', 11),
       ('AO', 12),
       ('CERO_A', 13),
       ('CERO_B', 14),
       ('CERO_C', 15),
       ('CERO_D', 16),
       ('CERO_Z', 17),
       ('USK_0', 18),
       ('USK_6', 19),
       ('USK_12', 20),
       ('USK_18', 21),
       ('GRAC_ALL', 22),
       ('GRAC_Twelve', 23),
       ('GRAC_Fifteen', 24),
       ('GRAC_Eighteen', 25),
       ('GRAC_TESTING', 26),
       ('CLASS_IND_L', 27),
       ('CLASS_IND_Ten', 28),
       ('CLASS_IND_Twelve', 29),
       ('CLASS_IND_Fourteen', 30),
       ('CLASS_IND_Sixteen', 31),
       ('CLASS_IND_Eighteen', 32),
       ('ACB_G', 33),
       ('ACB_PG', 34),
       ('ACB_M', 35),
       ('ACB_MA15', 36),
       ('ACB_R18', 37),
       ('ACB_RC', 38);

insert into game_categories
    (name, id)
values ('main_game', 0),
       ('dlc_addon', 1),
       ('expansion', 2),
       ('bundle', 3),
       ('standalone_expansion', 4),
       ('mod', 5),
       ('episode', 6),
       ('season', 7),
       ('remake', 8),
       ('remaster', 9),
       ('expanded_game', 10),
       ('port', 11),
       ('fork', 12);

insert into external_categories
    (name, id)
values ('steam', 1),
       ('gog', 5),
       ('youtube', 10),
       ('microsoft', 11),
       ('apple', 13),
       ('twitch', 14),
       ('android', 15),
       ('amazon_asin', 20),
       ('amazon_luna', 22),
       ('amazon_adg', 23),
       ('epic_game_store', 26),
       ('oculus', 28),
       ('utomik', 29),
       ('itch_io', 30),
       ('xbox_marketplace', 31),
       ('kartridge', 32),
       ('playstation_store_us', 36),
       ('focus_entertainment', 37);
